/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qualitycars;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author I
 */
public class FrameUPDATEcar extends javax.swing.JFrame {
    IndividualCar found =null;
    CarModel model;
    RentedCar foundRC;
    
    
    
    /**
     * Creates new form FrameADDnewCar
     */
    public FrameUPDATEcar() {
        initComponents();
        bodyTypeComboBox.setModel(new DefaultComboBoxModel<>(EnumBodyType.values()));
        EnumStatus[] twoItems = {EnumStatus.IN_THE_SHOP,EnumStatus.UNDER_MAINTENANCE};
        statusComboBox.setModel(new DefaultComboBoxModel<>(twoItems));
        this.carPanel.setVisible(false);
        this.statusPanel.setVisible(false);
        this.rentDatesPanel.setVisible(false);
        this.updatePanel.setVisible(false);
       
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carPanel = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        rentPerDaytField = new javax.swing.JTextField();
        expDateWOFDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel46 = new javax.swing.JLabel();
        colourTextField = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        bodyTypeComboBox = new javax.swing.JComboBox<>();
        yearTextField = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fuelTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        engineSizeTextField = new javax.swing.JTextField();
        enterModelButton = new javax.swing.JButton();
        manufactureTextField = new javax.swing.JTextField();
        updateModelDetailsButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        seatsTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        stockManagementButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        regNumberTextField = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        rentDatesPanel = new javax.swing.JPanel();
        rentDatePicker = new org.jdesktop.swingx.JXDatePicker();
        backDueDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        anotherCarButton = new javax.swing.JButton();
        statusPanel = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel45.setText("RENT PER DAY");

        jLabel46.setText("COLOUR");

        jLabel42.setText("(WOF) EXPIRY DATE");

        jLabel47.setText("YEAR OF MANUFACTURE");

        jLabel40.setText("BODY TYPE");

        jLabel4.setText("MODEL NAME");

        fuelTextField.setMaximumSize(new java.awt.Dimension(234, 234));
        fuelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 9)); // NOI18N
        jLabel9.setText("( Type new name and press ENTER to change the model )");

        jLabel2.setText("(number only)");

        engineSizeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineSizeTextFieldActionPerformed(evt);
            }
        });

        enterModelButton.setText("ENTER");
        enterModelButton.setBorderPainted(false);
        enterModelButton.setContentAreaFilled(false);
        enterModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterModelButtonActionPerformed(evt);
            }
        });

        manufactureTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufactureTextFieldActionPerformed(evt);
            }
        });

        updateModelDetailsButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        updateModelDetailsButton.setText("ONLY IF YOU NEED TO CHANGE THE MODEL DETAILS, PRESS HERE");
        updateModelDetailsButton.setBorderPainted(false);
        updateModelDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateModelDetailsButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("ENGINE SIZE");

        jLabel5.setText(" MANUFACTURER");

        seatsTextField.setMaximumSize(new java.awt.Dimension(234, 234));
        seatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText(" NUMBER OF SEATS");

        modelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText(" FUEL TYPE");

        javax.swing.GroupLayout carPanelLayout = new javax.swing.GroupLayout(carPanel);
        carPanel.setLayout(carPanelLayout);
        carPanelLayout.setHorizontalGroup(
            carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateModelDetailsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addGroup(carPanelLayout.createSequentialGroup()
                        .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearTextField)
                            .addComponent(rentPerDaytField)
                            .addComponent(bodyTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(carPanelLayout.createSequentialGroup()
                                .addComponent(expDateWOFDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(colourTextField)))
                    .addGroup(carPanelLayout.createSequentialGroup()
                        .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manufactureTextField)
                            .addComponent(seatsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(carPanelLayout.createSequentialGroup()
                                .addComponent(engineSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(fuelTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(carPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modelTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enterModelButton)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        carPanelLayout.setVerticalGroup(
            carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterModelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(manufactureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(engineSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(seatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fuelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateModelDetailsButton)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expDateWOFDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentPerDaytField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addGap(175, 175, 175))
        );

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(54, 78, 115));
        jLabel3.setText("UPDATE CAR:");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        stockManagementButton.setText("Stock management");
        stockManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockManagementButtonActionPerformed(evt);
            }
        });

        jLabel41.setText("REGISTRATION NUMBER");

        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel43.setText("DATE RENT STARTED");

        jLabel44.setText("DATE DUE BACK IN");

        jLabel1.setText("RENTED OUT");

        jLabel48.setText("STATUS");

        javax.swing.GroupLayout rentDatesPanelLayout = new javax.swing.GroupLayout(rentDatesPanel);
        rentDatesPanel.setLayout(rentDatesPanelLayout);
        rentDatesPanelLayout.setHorizontalGroup(
            rentDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentDatesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rentDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rentDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(rentDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backDueDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rentDatesPanelLayout.setVerticalGroup(
            rentDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentDatesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rentDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(rentDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentDatesPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel43))
                    .addGroup(rentDatesPanelLayout.createSequentialGroup()
                        .addComponent(rentDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rentDatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backDueDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))))
                .addContainerGap())
        );

        updateButton.setText("UPDATE CAR");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        anotherCarButton.setText("ANOTHER CAR");
        anotherCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anotherCarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anotherCarButton)
                .addContainerGap())
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(anotherCarButton))
                .addContainerGap())
        );

        jLabel39.setText("STATUS");

        statusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rentDatesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(carPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(updatePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(homeButton)
                                .addGap(59, 59, 59)
                                .addComponent(stockManagementButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(regNumberTextField)
                                .addGap(10, 10, 10)
                                .addComponent(searchButton)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentDatesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockManagementButton)
                    .addComponent(homeButton)
                    .addComponent(exitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
         
    try{
        if (found.getStatus().equals(EnumStatus.RENTED_OUT)) 
        {   carUpdate();
            Date rentDate = rentDatePicker.getDate();
            Date backDueDate = backDueDatePicker.getDate();
            
            if (rentDate.compareTo(backDueDate)>0)
                {JOptionPane.showMessageDialog(rootPane, "Check you rent dates.");} 
            else {
            found.setRentDate(rentDate);
            found.setBackDueDate(backDueDate);
            JOptionPane.showMessageDialog(rootPane, "The car was updated.");
            //          TO UPDATE RentedCars ArrayList
            String regNumber = regNumberTextField.getText();
            foundRC= FrameHOME.stock.searchRentedCarByRegNo(regNumber); 
            if (FrameHOME.stock.getRentedCars().isEmpty()==false && foundRC.getCar().getRegNumber().equals(regNumber)) 
              { foundRC.setCar(found);}              
            }
                
        } 
        else{carUpdate(); found.setStatus((EnumStatus)statusComboBox.getSelectedItem());

        JOptionPane.showMessageDialog(rootPane, "The car was updated.");}
     }
    
    catch (Exception ex) {JOptionPane.showMessageDialog(rootPane, 
            "1. Check YEAR OF MANUFACTURE. It cannot be negative and can contain only digits."
      + "\n   Cars didn't exist before 1886. A car couldn't be produced later than current year."
     + "\n\n             2. Check RENT PER DAY. It cannot be negative and can contain only digits.\n ");}
                  
    }//GEN-LAST:event_updateButtonActionPerformed
    private void carUpdate() throws Exception{
        String model=modelTextField.getText();
        String manufacturer=manufactureTextField.getText();
        int engineSize= Integer.parseInt(engineSizeTextField.getText() );
        int seats= Integer.parseInt(seatsTextField.getText() );
        CarModel foundM = FrameHOME.car.searchModel(model);
        EnumFuelType fuel = foundM.getFuelType();
        CarModel newModel = new CarModel(model,manufacturer,engineSize,seats,fuel);
        found.setCarModel(newModel);
        found.setExpDateWOF(expDateWOFDatePicker.getDate());
        found.setBodyType( (EnumBodyType)bodyTypeComboBox.getSelectedItem());
        found.setYear(Integer.parseInt(yearTextField.getText()));
        found.setColour(colourTextField.getText());
        found.setRentPerDay(Double.parseDouble(rentPerDaytField.getText()));
    }
            
    private void engineSizeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineSizeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engineSizeTextFieldActionPerformed

    private void manufactureTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufactureTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufactureTextFieldActionPerformed

    private void modelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextFieldActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System. exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        FrameHOME home = new FrameHOME();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void stockManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockManagementButtonActionPerformed
        // TODO add your handling code here:
        FrameMANAGE_Stock stock = new FrameMANAGE_Stock();
        stock.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_stockManagementButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String regNumber = regNumberTextField.getText();
        found = FrameHOME.stock.searchCarByRegNumber(regNumber); 
        
        if (found==null)
            {regNumberTextField.setBackground(Color.red);
                JOptionPane.showMessageDialog(rootPane, "The car with this number is not in database");}
        else{

            regNumberTextField.setBackground(Color.white);
            model= found.getCarModel();  //carModel is here
            modelTextField.setText(model.getModel());
            manufactureTextField.setText(model.getManufacturer());
            engineSizeTextField.setText(model.getEngineSize()+"");
            seatsTextField.setText(model.getSeats()+"");
            fuelTextField.setText(model.getFuelType()+"");
            
            manufactureTextField.setEditable(false);
            engineSizeTextField.setEditable(false);
            seatsTextField.setEditable(false);
            fuelTextField.setEditable(false);
            
          
            expDateWOFDatePicker.setDate(found.getExpDateWOF());
            bodyTypeComboBox.setSelectedItem(found.getBodyType());
            yearTextField.setText(found.getYear()+"");
            colourTextField.setText(found.getColour());
            rentPerDaytField.setText(found.getRentPerDay()+"");
            statusComboBox.setSelectedItem(found.getStatus());
            rentDatePicker.setDate(found.getRentDate());
            backDueDatePicker.setDate(found.getBackDueDate());
            
            if (found.getStatus().equals(EnumStatus.RENTED_OUT))
            {statusPanel.setVisible(false);rentDatesPanel.setVisible(true);
/*The next 2 blocks which I greyed out can be used to limit 
which information can be modified for the cars which are rented out.
The instruction has not specified it. */
//            modelTextField.setEditable(false);
//            expDateWOFDatePicker.setEditable(false);
//            bodyTypeComboBox.setEditable(false);
//            yearTextField.setEditable(false);
//            colourTextField.setEditable(false);
//            jLabel9.setVisible(false);
//            updateModelDetailsButton.setVisible(false);
            }
            else{statusPanel.setVisible(true);rentDatesPanel.setVisible(false);
            modelTextField.setEditable(true);
//            expDateWOFDatePicker.setEditable(true);
//            bodyTypeComboBox.setEditable(true);
//            yearTextField.setEditable(true);
//            colourTextField.setEditable(true);
//            jLabel9.setVisible(true);
//            updateModelDetailsButton.setVisible(true);
            }
            carPanel.setVisible(true);   
            updatePanel.setVisible(true); 
            regNumberTextField.setEditable(false);
            }
        
        
    }//GEN-LAST:event_searchButtonActionPerformed
    
    private void seatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsTextFieldActionPerformed

    private void enterModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterModelButtonActionPerformed
        // TODO add your handling code here:
        String model = modelTextField.getText();
        CarModel foundM = FrameHOME.car.searchModel(model);
        if (foundM==null)
        {   JOptionPane.showMessageDialog(rootPane, "This model doesn't exist. ");
            FrameADDmodel stock = new FrameADDmodel();
            modelTextField.setText("");
            manufactureTextField.setText("");
            engineSizeTextField.setText("");
            seatsTextField.setText("");
            fuelTextField.setText("");
            stock.setVisible(true);
            }           
        else{
            manufactureTextField.setText(foundM.getManufacturer());
            engineSizeTextField.setText(foundM.getEngineSize()+"");
            seatsTextField.setText(foundM.getSeats()+"");
            fuelTextField.setText(foundM.getFuelType()+"");
            
            manufactureTextField.setEditable(false);
            engineSizeTextField.setEditable(false);
            seatsTextField.setEditable(false);
            fuelTextField.setEditable(false);                       
            }
    }//GEN-LAST:event_enterModelButtonActionPerformed
    
    
    
    private void fuelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelTextFieldActionPerformed

    private void updateModelDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateModelDetailsButtonActionPerformed
        // TODO add your handling code here:
        FrameUPDATEmodel  updateModel =  new  FrameUPDATEmodel();
        //to pass data to FrameUPDATEmodel
        updateModel.my_update(modelTextField.getText(),manufactureTextField.getText(),
                              Integer.parseInt(engineSizeTextField.getText()),
                              Integer.parseInt(seatsTextField.getText()),
                               fuelTextField.getText()); 
        updateModel.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_updateModelDetailsButtonActionPerformed

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBoxActionPerformed

    private void anotherCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anotherCarButtonActionPerformed
        // TODO add your handling code here:
        regNumberTextField.setEditable(true);
        carPanel.setVisible(false);   
        updatePanel.setVisible(false); 
        statusPanel.setVisible(false);
        rentDatesPanel.setVisible(false);

    }//GEN-LAST:event_anotherCarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUPDATEcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUPDATEcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUPDATEcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUPDATEcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUPDATEcar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anotherCarButton;
    private org.jdesktop.swingx.JXDatePicker backDueDatePicker;
    private javax.swing.JComboBox<qualitycars.EnumBodyType> bodyTypeComboBox;
    private javax.swing.JPanel carPanel;
    private javax.swing.JTextField colourTextField;
    private javax.swing.JTextField engineSizeTextField;
    private javax.swing.JButton enterModelButton;
    private javax.swing.JButton exitButton;
    private org.jdesktop.swingx.JXDatePicker expDateWOFDatePicker;
    private javax.swing.JTextField fuelTextField;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField manufactureTextField;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JTextField regNumberTextField;
    private org.jdesktop.swingx.JXDatePicker rentDatePicker;
    private javax.swing.JPanel rentDatesPanel;
    private javax.swing.JTextField rentPerDaytField;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField seatsTextField;
    private javax.swing.JComboBox<EnumStatus> statusComboBox;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JButton stockManagementButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateModelDetailsButton;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
