/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qualitycars;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author I
 */
public class FrameRENTcar extends javax.swing.JFrame {
        Client found;

    /**
     * Creates new form FrameRENTcar
     */
    public FrameRENTcar() {
        initComponents();
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        manufacturertTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        engineSizeTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        seatsTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fuelTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        rentDatePicker = new org.jdesktop.swingx.JXDatePicker();
        backDueDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        regNumberComboBox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enterModelButton = new javax.swing.JButton();
        addressTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        licenseNumberField = new javax.swing.JTextField();
        licenseTypeField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        licenseExpDatePicker = new org.jdesktop.swingx.JXDatePicker();
        birthDatePicker = new org.jdesktop.swingx.JXDatePicker();
        modelComboBox = new javax.swing.JComboBox<>();
        genderTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        enterIdButton = new javax.swing.JButton();
        rentManagementButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("MANUFACTURER");

        manufacturertTextField.setEditable(false);
        manufacturertTextField.setBorder(null);

        jLabel3.setText("ENGINE SIZE");

        engineSizeTextField.setEditable(false);
        engineSizeTextField.setBorder(null);
        engineSizeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineSizeTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("No OF SEATS");

        seatsTextField.setEditable(false);
        seatsTextField.setBorder(null);
        seatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("FUEL TYPE");

        fuelTextField.setEditable(false);
        fuelTextField.setBorder(null);

        modelTable.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        modelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "REG No", "WOF EXPIEY DATE", "BODY TYPE", "YEAR", "COLOUR", "RENT PER DAY, $"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(modelTable);
        if (modelTable.getColumnModel().getColumnCount() > 0) {
            modelTable.getColumnModel().getColumn(0).setResizable(false);
            modelTable.getColumnModel().getColumn(1).setResizable(false);
            modelTable.getColumnModel().getColumn(2).setResizable(false);
            modelTable.getColumnModel().getColumn(3).setResizable(false);
            modelTable.getColumnModel().getColumn(4).setResizable(false);
            modelTable.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel6.setText("CHOOSE A CAR BY ITS REGISTRATION NUMBER");

        jLabel43.setText("DATE RENT STARTED");

        jLabel44.setText("DATE DUE BACK IN");

        jLabel18.setText("CARS AVAILABLE FOR RENT:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(regNumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rentDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backDueDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(manufacturertTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(engineSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(12, 12, 12)
                                .addComponent(seatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fuelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18))
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(manufacturertTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(engineSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(fuelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(regNumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(backDueDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(54, 78, 115));
        jLabel7.setText("RENT A CAR");

        jLabel1.setText("CHOOSE A MODEL FOR RENT");

        enterModelButton.setText("Enter");
        enterModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterModelButtonActionPerformed(evt);
            }
        });

        addressTextField.setEditable(false);

        jLabel13.setText("ADDRESS");

        phoneTextField.setEditable(false);

        jLabel14.setText("PHONE No");

        jLabel11.setText("GENDER");

        nameTextField.setEditable(false);

        jLabel10.setText("NAME");

        jLabel12.setText("DATE OF BIRTH");

        jLabel15.setText("LICENSE No");

        licenseNumberField.setEditable(false);
        licenseNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseNumberFieldActionPerformed(evt);
            }
        });

        licenseTypeField.setEditable(false);
        licenseTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseTypeFieldActionPerformed(evt);
            }
        });

        jLabel16.setText("LICENSE TYPE");

        jLabel17.setText("LICENSE EXPIRY DATE");

        licenseExpDatePicker.setEditable(false);

        birthDatePicker.setEditable(false);

        modelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelComboBoxActionPerformed(evt);
            }
        });

        genderTextField.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licenseNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)))
                    .addComponent(nameTextField))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(licenseTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(licenseExpDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(birthDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderTextField)))
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterModelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(birthDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(licenseTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(licenseExpDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(licenseNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(enterModelButton)
                    .addComponent(modelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel8.setText("CLIENT DATA");

        jLabel9.setText("Enter client ID");

        enterIdButton.setText("Enter");
        enterIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterIdButtonActionPerformed(evt);
            }
        });

        rentManagementButton.setText("Rental management");
        rentManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentManagementButtonActionPerformed(evt);
            }
        });

        rentButton.setText("RENT");
        rentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(rentButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rentButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(75, 75, 75)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterIdButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addGap(181, 181, 181)
                .addComponent(rentManagementButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterIdButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeButton)
                    .addComponent(exitButton)
                    .addComponent(rentManagementButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterModelButtonActionPerformed
        // TODO add your handling code here:
        
        if (FrameHOME.stock.noCarsForRent())
           {JOptionPane.showMessageDialog(rootPane, "There are no cars for rent");}
        else {
            String model = modelComboBox.getSelectedItem().toString();
            CarModel foundM = FrameHOME.car.searchModel(model);
            manufacturertTextField.setText(foundM.getManufacturer());
            engineSizeTextField.setText(foundM.getEngineSize()+"");
            seatsTextField.setText(foundM.getSeats()+"");
            fuelTextField.setText(foundM.getFuelType()+"");
            DefaultTableModel table = (DefaultTableModel) modelTable.getModel();
            Object rowColumns[]=new Object[6];
            table.setRowCount(0);  
            ArrayList<String> temporaryArrayList= new ArrayList();
            for(int i=0;i<FrameHOME.stock.getCars().size();i++)
            {
            if (FrameHOME.stock.getCars().get(i).getStatus().equals(EnumStatus.IN_THE_SHOP)&&FrameHOME.stock.getCars().get(i).getCarModel().getModel().equals(model))                                   
                {   
                rowColumns[0]= FrameHOME.stock.getCars().get(i).getRegNumber();
                rowColumns[1]= FrameHOME.stock.getCars().get(i).getExpDateWOF();
                rowColumns[2]= FrameHOME.stock.getCars().get(i).getBodyType();
                rowColumns[3]= FrameHOME.stock.getCars().get(i).getYear();
                rowColumns[4]= FrameHOME.stock.getCars().get(i).getColour();
                rowColumns[5]= FrameHOME.stock.getCars().get(i).getRentPerDay();
                table.addRow(rowColumns);
                temporaryArrayList.add(FrameHOME.stock.getCars().get(i).getRegNumber());
                }
            }
            String[] ArrayRegNumbers = new String[temporaryArrayList.size()]; 
            ArrayRegNumbers = temporaryArrayList.toArray(ArrayRegNumbers);    
            regNumberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(ArrayRegNumbers));

            if (temporaryArrayList.isEmpty())
            {jPanel3.setVisible(false);
                JOptionPane.showMessageDialog(rootPane,"This model doesn't have cars for rent, please choose another available model");}
            else{jPanel2.setVisible(true);
            jPanel3.setVisible(true);}
        }
    }//GEN-LAST:event_enterModelButtonActionPerformed


    
    private void engineSizeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineSizeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engineSizeTextFieldActionPerformed

    private void seatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsTextFieldActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System. exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        FrameHOME home = new FrameHOME();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void rentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentButtonActionPerformed
        // TODO add your handling code here:
        String regNumber = regNumberComboBox.getSelectedItem().toString();
        IndividualCar foundCar = FrameHOME.stock.searchCarByRegNumber(regNumber); 
        
        Date rentDate = rentDatePicker.getDate();
        Date backDueDate = backDueDatePicker.getDate();
        while (rentDate==null||backDueDate==null)
        {JOptionPane.showMessageDialog(rootPane, "Set rent dates."); break;}
        if (rentDate!=null&&backDueDate!=null)
        {  
            if ( rentDate.compareTo(backDueDate)>0)
                {JOptionPane.showMessageDialog(rootPane, "Check you rent dates.");} 
            else{
                foundCar.setRentDate(rentDate);
                foundCar.setBackDueDate(backDueDate);
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                foundCar.setStatus(EnumStatus.RENTED_OUT);
                JOptionPane.showMessageDialog(rootPane, "The car # "+regNumber+" ("+foundCar.getColour()+" "
                        +foundCar.getCarModel().getModel()+" ) was rented. "); 
                 RentedCar rentedCar = new RentedCar(found,foundCar); //or client?
                 FrameHOME.stock.addRentedCar(rentedCar); 
                 
                 Date todayIs = new Date();
                 SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
                 if(!sdf.format(todayIs).equals(sdf.format(found.getDate()))) 
                 {found.setNewOrOld("old");}
                }
        }
        

    }//GEN-LAST:event_rentButtonActionPerformed

    private void enterIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterIdButtonActionPerformed
        // TODO add your handling code here:
        if (idTextField.getText().equals(""))
        {JOptionPane.showMessageDialog(rootPane, "Please enter client ID.");}
        else{
            int id = Integer.parseInt(idTextField.getText());
            found = FrameHOME.stock.searchClient(id);
             if (found==null)
            {   idTextField.setBackground(Color.red);
                JOptionPane.showMessageDialog(rootPane, "Client with such ID is not in our database. Please add client's data.");
                FrameADDclient client = new FrameADDclient();
                client.my_updateAddClientId(id); //to pass data to FrameADDclient
                client.setVisible(true);
                idTextField.setBackground(Color.white);
                 }
             else
             {  
                 ArrayList<IndividualCar> car = FrameHOME.stock.getCars();
            int x = 0;
            for(int i=0;i<car.size();i++)
                if (car.get(i).getStatus().equals(EnumStatus.IN_THE_SHOP))
                {x++;}
            if (x==0){JOptionPane.showMessageDialog(rootPane, "There are no cars to rent.");} 
            else{

                nameTextField.setText(found.getPersonName());
                birthDatePicker.setDate(found.getBirthDate());
                genderTextField.setText(found.getGender().toString());
                phoneTextField.setText(found.getPhone());
                addressTextField.setText(found.getAddress());
                licenseNumberField.setText(found.getLicenseNumber());
                licenseTypeField.setText(found.getLicenseType());
                licenseExpDatePicker.setDate(found.getLicenseExpDate());

                String[] ArrayModels = new String [FrameHOME.car.getModelArrayList().size()];
    //            System.out.println(FrameHOME.car.getModels().size());
                for (int i=0; i<FrameHOME.car.getModelArrayList().size();i++){ArrayModels[i]=FrameHOME.car.getModelArrayList().get(i).getModel();}
    //            System.out.println(Arrays.toString(ArrayModels));
                modelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(ArrayModels));

                 jPanel1.setVisible(true);
             }}
        }
    }//GEN-LAST:event_enterIdButtonActionPerformed

    private void licenseNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNumberFieldActionPerformed

    private void licenseTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseTypeFieldActionPerformed

    private void rentManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentManagementButtonActionPerformed
        // TODO add your handling code here:
        FrameMANAGE_Rent stock = new FrameMANAGE_Rent();
        stock.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rentManagementButtonActionPerformed

    private void modelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelComboBoxActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_modelComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRENTcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRENTcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRENTcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRENTcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRENTcar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private org.jdesktop.swingx.JXDatePicker backDueDatePicker;
    private org.jdesktop.swingx.JXDatePicker birthDatePicker;
    private javax.swing.JTextField engineSizeTextField;
    private javax.swing.JButton enterIdButton;
    private javax.swing.JButton enterModelButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField fuelTextField;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JButton homeButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private org.jdesktop.swingx.JXDatePicker licenseExpDatePicker;
    private javax.swing.JTextField licenseNumberField;
    private javax.swing.JTextField licenseTypeField;
    private javax.swing.JTextField manufacturertTextField;
    private javax.swing.JComboBox<String> modelComboBox;
    private javax.swing.JTable modelTable;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JComboBox<String> regNumberComboBox;
    private javax.swing.JButton rentButton;
    private org.jdesktop.swingx.JXDatePicker rentDatePicker;
    private javax.swing.JButton rentManagementButton;
    private javax.swing.JTextField seatsTextField;
    // End of variables declaration//GEN-END:variables
}
